# Generated by Django 4.0.3 on 2022-03-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='name',
            field=models.CharField(default='kakala', max_length=50),
        ),
    ]
